### ISSUE TITLE
Fork the linked-connections-server

### ISSUE THREAD

**Issue by DemianD** [osoc21/technical-support#10]
**Is your request related to a problem? Please describe.**

We need to fork the https://github.com/linkedconnections/linked-connections-server/tree/master but we don't have permissions to do so.

**Describe the solution you'd like**

Can you fork the repository in the osoc organization, and assign the admin role to me?

Thank you

**Comment by jbelien** [comment]
No worries, I'll take care of it.

To what team should I assign it ? @osoc21/linked-out or @osoc21/wepod ?

**Comment by jbelien** [comment]
- ✅ https://github.com/osoc21/linked-connections-server forked
- ✅ You've been given admin access

**Comment by DemianD** [comment]
Hey, thank you. I assigned the `@osoc21/linked-out`.
