### ISSUE TITLE
Deployment - Dedicated server & Domain name for the Road Base project

### ISSUE THREAD

**Issue by jodiDL** [osoc21/technical-support#11]
For the roadbase project deployment we would like a dedicated server and domain name.

**Server:**
Since we are unable to use the digital ocean App Platform due to the complexity of our application, a basic Ubuntu droplet (5USD/month) would be the best way to go.

**Domain name:**
If possible:
 _roadbase.osoc.be_  for the frontend.
_roadbase-api.osoc.be_ for the API.

**Comment by jbelien** [comment]
> Since we are unable to use the digital ocean App Platform due to the complexity of our application

Could you please investigate "Dockerization" of your API ?

> roadbase.osoc.be for the frontend.

What technology is used for your frontend ?
Can it be statically built ?

**Comment by jbelien** [comment]
Sub domain names are of course not an issue.

**Comment by jodiDL** [comment]
> > Since we are unable to use the digital ocean App Platform due to the complexity of our application
> 
> Could you please investigate "Dockerization" of your API ?
> 
> > roadbase.osoc.be for the frontend.
> 
> What technology is used for your frontend ?
> Can it be statically built ?

All of our services are indeed dockerized, but if I understand correctly the App Platform is used for the deployment of 1 docker image, while we have multiple containers (probably even a few more to come) to deploy using docker compose.. 

I do think the frontend in Ember can be statically build, but since we need multiple containers anyway I think it would make more sense to deploy everything on a droplet using Nginx. 

We would also need to load the SPARQL data from an lblod repo on deployment, which I don't think is possible using the app platform :)

**Comment by jbelien** [comment]
> All of our services are indeed dockerized, but if I understand correctly the App Platform is used for the deployment of 1 docker image, while we have multiple containers (probably even a few more to come) to deploy using docker compose..

Digital Ocean App Platform can deploy several Dockerfiles, that part is not an issue.

> I do think the frontend in Ember can be statically build, but since we need multiple containers anyway I think it would make more sense to deploy everything on a droplet using Nginx.

If you have a Dockerfile for the frontent that should work.

> We would also need to load the SPARQL data from an lblod repo on deployment, which I don't think is possible using the app platform :)

You can put that process in your Dockerfile.

So, I'll reiterate my request : could you please investigate creating Dockerfiles for your components ?

**Comment by jodiDL** [comment]
We have dockerfiles :)

I just fear we might get ourselves stuck in the long run if we use the App platform, so I would prefer a droplet because we have much more freedom with that. I have experience in deploying to digital ocean droplets and setting up the automatic deploys, so no issue there.

**Comment by jbelien** [comment]
Okay for a droplet but, before deploying it, I'll need a full documentation (`INSTALL.md` file for instance) with all the setup steps.

**Comment by jodiDL** [comment]
Setup steps for deploying the droplet like creating the users or what exactly would you need?

**Comment by jbelien** [comment]
When your client will want to deploy everything itself, it must not have to contact you (or if the droplet needs to be setup again after a crash).
You need to provide an how-to with all the steps to follow so **everything** is working properly.

(unrelated to where the droplet is started, just the steps once you're connected to the server)

**Comment by jodiDL** [comment]
I will indeed document every step! That might also be very interesting for anyone else to follow (including myself ;) )

**Comment by jodiDL** [comment]
@jbelien Do you need these steps before setting up the server? I would document this while doing the deployment :)

**Comment by jbelien** [comment]
I indeed need these steps **before** creating the droplet !
It can of course be improved while deploying if there are information missing.

**Comment by jodiDL** [comment]
@jbelien 
https://github.com/osoc21/RoadBase/blob/master/misc/deployment/README.md

More documentation to be added while deploying, but we would realy need the droplet now :)

**Comment by jbelien** [comment]
@jodiDL Send me your public SSH key on Discord!

**Comment by jbelien** [comment]
🚀 
- IP address of your server: `164.90.192.163`
- Domain name: `roadbase.osoc.be`

**Comment by jbelien** [comment]
@jodiDL Your SSH key is now added !
