### ISSUE TITLE
Rename repository of Belbadges

### ISSUE THREAD

**Issue by jeborsel** [osoc21/technical-support#12]
Can you rename the [Belbadges](https://github.com/osoc21/Belbadges) repository to "edubadges-be" (I don't have the permissions to do so) ?

Would be good so naming is in line with where code is being developed : [here](https://github.com/edubadges-be) 
We will add readme with explanation of project within osoc21 & outside of osoc

**Comment by jbelien** [comment]
✅ Done: https://github.com/osoc21/edubadges-be

**Warning:** if you already cloned the repository locally, you'll have to update the remote origin (or re-clone the repository).
