### ISSUE TITLE
Create wepod-tech repo for the IDLab-Reclaim your data team

### ISSUE THREAD

**Issue by vanakenm** [osoc21/technical-support#13]
**Is your request related to a problem? Please describe.**
We have some technical info and samples I'd like to share with the students

**Describe the solution you'd like**
We'd like a new repo to host those named wepod-tech

**Describe alternatives you've considered**
Could use Google Doc but we want  code too. Don't want to "pollute" our main codebase

**Additional context**
Thanks a lot for your support!

**Comment by jbelien** [comment]
✅ https://github.com/osoc21/wepod-tech
