### ISSUE TITLE
Second repo for Future of Work

### ISSUE THREAD

**Issue by Zenigame2** [osoc21/technical-support#16]
**Is your request related to a problem? Please describe.**
We are working on a second application for Future of Work. It might be better practise to have a second repo for the second application.

**Describe the solution you'd like**
We would like a second repo for Future of Work in the osoc21 organisation.

**Describe alternatives you've considered**
I tried to create one myself but I don't have the permissions

**Additional context**
/

**Comment by jbelien** [comment]
No worries, what's the name of the repository you want to create ?

**Comment by Zenigame2** [comment]
The name is Future-of-Work-Bino

**Comment by jbelien** [comment]
✅ https://github.com/osoc21/Future-of-Work-Bino
