### ISSUE TITLE
Deployment - SDK Demo  | LDES Project

### ISSUE THREAD

**Issue by D34DPlayer** [osoc21/technical-support#17]
**Is your request related to a problem? Please describe.**
For the demo day, we'd like to showcase our SDK with an example of an use case. 

**Describe the solution you'd like**
This demo would require a MongoDB database, a postgres database and a container running our SDK.

**Describe alternatives you've considered**
Anything that allows us to have those 3 things should work, our SDK is compatible with docker-compose and Kubernetes.
However, deploying a Kubernetes cluster for this demo may be overkill.

**Additional context**
Persistance of the databases and a connection between the databases and the SDK are, of course, needed.

**Comment by jbelien** [comment]
Considering the number of components, I think a DigitalOcean Droplet would be the best option.

- Could you prepare a `INSTALL.md` file with all the instructions to setup all the components in a server (installation + configuration) ?
- If I give you (or your coach) access to a droplet (= server), can you install everything on your own ?

**Comment by D34DPlayer** [comment]
Sure, I'll work on that INSTALL.md. And I can set up everything up myself in the droplet.

**Comment by jbelien** [comment]
Ping me here when you have your `INSTALL.md` ready and I'll give you access to the droplet.

**Comment by D34DPlayer** [comment]
@jbelien The install documentation can be found [here](https://github.com/osoc21/ldes2service/blob/readme-update/INSTALL.md) and the SDK documentation on the main README.

**Comment by jbelien** [comment]
Droplet creation on its way!

@D34DPlayer Send me your SSH public key on Discord.

**Comment by jbelien** [comment]
🚀 
- IP address: `178.128.242.87`
- Domain name: `ldes.osoc.be`

**Comment by DemianD** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwpt2fy9lIfi25UCqhkLXrHCDyPIWqM9kgELT5hxPt0GGLws3S08JpK1xJOeLw8uaBMxdBBcTIuLCngrCkQEo6jMhBDTAaiMaUsfffHKpmnoXFmZxoFbR5LH9fUyxRHTmGjmtBhMlFYnrGNTn9AWSBlndAsynS9o4svZ2uvAKyy3N14L7hPD7941WC5SO2QnM4BGb233OiLVmeEKJ8by42swu6+y7wylr7WGb0AcCefk9NrYnLMxL65xh9DVVkmdr3FDxA+E7Cc+B64YRa1XL3X1Tyjqu2W3K0xfaS3KYsnlluo/Y3h1o41QTfYXZaQGheWRd+0kGfKO8dASd8UvevfQrmgvkyIYW/lG37Pgy6RkVfHc0YTVG5gVQY8q5UxVhMoza/c2Mf2V94S7Jbdk/cg+cN35q3tSZiaHUQ8vtoANirMPcIGAIphhGUSJQgd/UvCB8xiS1xb2CsXTG837lOY3rDgHL61sVWpJlO9E+OcgWYcksgFqRIdkBe0ljvZ3aj6GzJoSzbYElWHQ5IOGTFFdPzJKUXbcZxBuRB5Q04YB7YgqH72Reqa1utDnqEMRly5NfoGSKcqoMvcGET+dZINRuAHnkMvPvpBJeVH1X5JBbQEqOWOXlcbPPqCnEsZ/gBp06Kn3Yg/7Q/CYNEp9EF5MO4uSpgwkoIpcs6VugJHw== demian@live.be
```

**Comment by jbelien** [comment]
@DemianD SSH key has been added, you should now have access to the droplet!

**Comment by jbelien** [comment]
@D34DPlayer SSH key has been added, you should now have access to the droplet!
