### ISSUE TITLE
Replace Artevelde logo on osoc website

### ISSUE THREAD

**Issue by mietcls** [osoc21/technical-support#18]
**Is your request related to a problem? Please describe.**
Artevelde updated their logo, and requested a change. I uploaded the old one.

**Describe the solution you'd like**
Use the English SVG logo [https://help.osoc.be/osoc21/projects-partners/artevelde#logos](https://help.osoc.be/osoc21/projects-partners/artevelde#logos)

**Describe alternatives you've considered**
I've asked if they mind. They do.

**Additional context**
Thanks Jonathan!

**Comment by jbelien** [comment]
No worries, could you upload the logo here ?

**Comment by jbelien** [comment]
Moved to https://github.com/opensummerofcode/website/issues/154

**Comment by mietcls** [comment]
It doesn't support SVG; but I can give you this link: [https://gblobscdn.gitbook.com/assets%2F-Mbef5VGwnuL5Dcf_gDG%2F-Mf3tjRonknnu5D3j3_w%2F-Mf3uPYh_LCAfKG6imxS%2Flogo-artevelde-eng.svg?alt=media&token=2f2624b7-c60e-48ea-85d6-2846e5c12a9f](https://gblobscdn.gitbook.com/assets%2F-Mbef5VGwnuL5Dcf_gDG%2F-Mf3tjRonknnu5D3j3_w%2F-Mf3uPYh_LCAfKG6imxS%2Flogo-artevelde-eng.svg?alt=media&token=2f2624b7-c60e-48ea-85d6-2846e5c12a9f)

**Comment by mietcls** [comment]
Oh, my link didn't come through!

**Comment by jbelien** [comment]
Okay, got it! See https://github.com/opensummerofcode/website/issues/154 for follow up!
