### ISSUE TITLE
Not enough permissions to fork existing repositories. 

### ISSUE THREAD

**Issue by DemianD** [osoc21/technical-support#2]
**Is your request related to a problem? Please describe.**

We need to fork a repository, instead of putting a full copy on GitHub: 
https://github.com/Informatievlaanderen/ldes2service

We don't have permissions to fork it to this organization:
"You don’t have permission to fork to these organizations:"

**Describe the solution you'd like**

Someone that clones the repository, and add it to our team.

**Comment by jbelien** [comment]
Done: https://github.com/osoc21/ldes2service
