### ISSUE TITLE
WePod deployed URL

### ISSUE THREAD

**Issue by Speedbuilder** [osoc21/technical-support#20]
Not sure if we already sent the URL to our deployed version, but here it is just to make sure: [https://wepod.osoc.be/#/](https://wepod.osoc.be/#/)

**Comment by jbelien** [comment]
Thanks @Speedbuilder !

Is there any API deployed ?
If so, what's the URL of the API ?

**Comment by Speedbuilder** [comment]
Nope there's no API, all the work is done in the front-end baby!
