### ISSUE TITLE
Crowdy deployed URLs

### ISSUE THREAD

**Issue by ezer-i** [osoc21/technical-support#22]
Here is the links:

Frontend: ``https://crowdy-osoc.herokuapp.com/``, ``http://crowdy.osoc.be/``
Api URL: ``https://crowdy-server-backend.herokuapp.com/``, ``http://api.crowdy.osoc.be/``

Note: To access the graphql playgroung: ``apiUrl/graphql``

**Comment by jbelien** [comment]
Thanks @ezering !

Question: https://crowdy-server-backend.herokuapp.com/graphql return a `400 Bad Request` code.
Is there a way to fix that ?
Or give me a URL for the back-end that returns a 200 code ?

**Comment by ezer-i** [comment]
This link : `` https://crowdy-server-backend.herokuapp.com/graphql`` works fine...I can access the graphql playground.
But you need to add a mutation or a query to make it work...it's doing constant refreshs in the background.

Here is an example: 

![Capture --- api](https://user-images.githubusercontent.com/87004888/127468098-5f78020b-8ce5-4864-9667-76b117b2281c.PNG)
