### ISSUE TITLE
Deployed project VLIZ (Final-Improved-String-pHarser)

### ISSUE THREAD

**Issue by Stillpatience** [osoc21/technical-support#24]
You can find our project deployed at https://fish.osoc.be/

**Comment by jbelien** [comment]
Thanks @Stillpatience !

Do you have an API ?
If so, what's the URL of that API ?

**Comment by Stillpatience** [comment]
https://fish.osoc.be/ is the entry point for the API
https://fish.osoc.be/swagger/ contains the documentation
