### ISSUE TITLE
More permissions on the ldes2service repository

### ISSUE THREAD

**Issue by DemianD** [osoc21/technical-support#4]
**Is your request related to a problem? Please describe.**

Is it possible to give the admin privileges on the `ldes2service` so it's possible to setup Github Actions secrets, and add protected branches?

**Comment by jbelien** [comment]
No worries, who needs admin privileges ?

**Comment by DemianD** [comment]
You can give me `admin` privileges. Thx!

**Comment by jbelien** [comment]
Done! ✅
