### ISSUE TITLE
Desktop pc - needs a linux distro, try it out, pc crashes completely

### ISSUE THREAD

**Issue by wardbeyens** [osoc21/technical-support#5]
**Is your request related to a problem? Please describe.**
problem to work for OSOC

**Describe the solution you'd like**
Someone to help me with the correct bios like secure boot disabled and where it all goes wrong, i have a few USB with ubuntu and pop os

**Describe alternatives you've considered**
Working on my pc but it is much slower

**Additional context**
Sad pc https://imgur.com/gallery/T50R2bk

**Comment by jbelien** [comment]
Hello @wardbeyens ,

First things first, could you accept the invitation to join GitHub "osoc21" organization sent a few days ago, so I can assign you to your team ?

What's the issue exactly ?
Are you looking to reset your PC and install a clean new Linux distribution ?

**Comment by wardbeyens** [comment]
Normally the invitation is done.

And yes, ideal solution would be a new clean installation of pop_os

**Comment by jbelien** [comment]
> Normally the invitation is done.

Confirmed.

> And yes, ideal solution would be a new clean installation of pop_os

This is out of my jurisdiction.
I've asked to create an "os"/"linux" help channel so I can forward your request to everyone. :)

**Comment by Denperidge** [comment]
Apparently there's a bootloader-fixer made by the pop_os devs, you can perhaps try to give that a spin?
https://support.system76.com/articles/bootloader

**Comment by jbelien** [comment]
Is your problem fixed @wardbeyens ?

If not, there is now a `#linux-macos-windows` help channel on Discord.
I forwarded your message there.
