### ISSUE TITLE
WePod would like a second GitHub repo called wepod-sandbox to push experiments

### ISSUE THREAD

**Issue by vanakenm** [osoc21/technical-support#6]
**Is your request related to a problem? Please describe.**
We have a lot of small technical experiment to conduct and would like to push them to github to share between us.

**Describe the solution you'd like**
We'd like a wepod-sandbox repo under the osoc21 with access for our team

**Describe alternatives you've considered**
We can use our personal accounts, but we'd prefer it to be under the osoc umbrella

**Additional context**
N/A

Thanks!

**Comment by jbelien** [comment]
Done: https://github.com/osoc21/wepod-sandbox ✅
