### ISSUE TITLE
Repository permissions

### ISSUE THREAD

**Issue by archived-m** [osoc21/technical-support#7]
**Is your request related to a problem? Please describe.**
Could I be added to the team "The Deloitted Spaghettis"? I took over coaching from Michael :)

**Comment by jbelien** [comment]
Done! ✅ https://github.com/orgs/osoc21/teams/the-deloitted-spaghettis

Should I remove Michael ?

**Comment by archived-m** [comment]
Yup, you can!
Thanks :)
