### ISSUE TITLE
Permissions for project repo (adding a PAT and for future deployment stuff)

### ISSUE THREAD

**Issue by juliavdkris** [osoc21/technical-support#8]
**Is your request related to a problem? Please describe.**
I would like to add [an action from the marketplace](https://github.com/marketplace/actions/epic-issues-for-github) to create "epic" issues (high-level issues that can be split into several more detailed tasks). It requires adding a `GITHUB_TOKEN` secret (personal access token with permission to create/manage issues).

**Describe the solution you'd like**
Could I maybe have some more permissions to manage the project's repository and add a personal access token? This would also be useful in the future for setting up our deployment etc.

**Describe alternatives you've considered**
Otherwise we can of course always manage "epic" issues manually, but this seems like a nice tool :)

**Comment by jbelien** [comment]
Admin access has been granted to @jodiDL for https://github.com/osoc21/RoadBase

**Comment by jbelien** [comment]
You might not even need the GitHub Actions workflow anymore.

Announced yesterday: <https://github.blog/changelog/2021-06-23-whats-new-with-github-issues/#%E2%9C%A8-new---break-issues-into-actionable-tasks>

**Comment by juliavdkris** [comment]
Oohhh nice, I signed up for the beta! Still, thanks for adding Jodi as admin, means we won't have to bother you when setting up our deployment :)

**Comment by jbelien** [comment]
The "Break issues into actionable tasks" seems to be already available (public beta), no need to be registered in the beta.
I didn't check (yet) though.

**Comment by juliavdkris** [comment]
Oh yep, you're right! I just scanned through the blog post and saw a link with "sign up for the beta now". Though the new project management thing looked really cool as well!
