### ISSUE TITLE
Hi, can you change our name from 'Arvesta-Farmer-Hackathon' to 'Arvesta's Digital Innovation Hackathon'? Thank you!

### ISSUE THREAD

**Issue by Lauvos** [osoc21/technical-support#9]
**Is your request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbelien** [comment]
Repository has been renamed: https://github.com/osoc21/Arvesta-s-Digital-Innovation-Hackathon

⚠️ If you already cloned the repository, you will have to update the remote origin (or re-cloned it since there is nothing in it yet).
